services:
  - type: web
    name: auth-service
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_REDIS_HOST
        value: redis-16589.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
      - key: SPRING_REDIS_PORT
        value: "16589"
      - key: SPRING_REDIS_PASSWORD
        value: IR6vR80riusw3BYH9j0BNXlb2Tf744lF
      - key: SPRING_RABBITMQ_HOST
        value: amqps://eamtmpan:elig7hs1qUHpa9EXFHUcM2ygKrzLkQID@armadillo.rmq.cloudamqp.com/eamtmpan
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        value: eamtmpan
      - key: SPRING_RABBITMQ_PASSWORD
        value: elig7hs1qUHpa9EXFHUcM2ygKrzLkQID
      # Cập nhật các giá trị này với thông tin RDS AWS MariaDB của bạn
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:mariadb://hsocial.cd0ce8sgc7vf.ap-southeast-1.rds.amazonaws.com:3306/hsocial"
      - key: SPRING_DATASOURCE_USERNAME
        value: "admin"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "sapassword"