name: Build and Deploy

on:
  push:
    branches: [ production ]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Build and push Docker images
      run: |
        gcloud builds submit --config=cloudbuild.yaml
        
    - name: Deploy backend services
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        gcloud run deploy auth-service --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hsocial-repo/auth-service:${SHORT_SHA} --platform managed --region asia-southeast1 --allow-unauthenticated
        # Lặp lại cho các service khác

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build
      run: |
        cd frontend
        npm run build
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
