name: CI/CD Pipeline - AuthService

on:
  push:
    branches: [ main, master, production ]
  pull_request:
    branches: [ main, master, production ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./backend/AuthService

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build và test AuthService
        run: |
          cd ./backend/AuthService
          ./gradlew build -x test

  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-lasted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image version
        run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

      - name: Build and push AuthService image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/AuthService
          push: true
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hsocial-auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hsocial-auth-service:${{ env.VERSION }}

      - name: Lưu version image
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: echo "VERSION=${{ env.VERSION }}" >> $GITHUB_OUTPUT
        id: version

  deploy:
    needs: build-docker-image
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml và deploy.sh to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml,deploy.sh"
          target: "/home/${{ secrets.SSH_USERNAME }}/hsocial-app"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/hsocial-app
            chmod +x deploy.sh
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            ./deploy.sh

      - name: Kiểm tra trạng thái services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/hsocial-app
            docker-compose ps
            echo "Deployment completed at $(date)"

  notify:
    needs: [deploy]
    runs-on: self-hosted
    if: always()

    steps:
      - name: Thông báo thành công
        if: ${{ needs.deploy.result == 'success' }}
        run: echo "Deployment AuthService đã hoàn tất thành công!"

      - name: Thông báo thất bại
        if: ${{ needs.deploy.result == 'failure' }}
        run: echo "Deployment AuthService thất bại!"
